version: '2.1'

services:

    server:
        build:
            context: ./docker/php
            dockerfile: ${DOCKERFILE_PHP}
            args:
                TIMEZONE: ${TIMEZONE}
        depends_on:
            - db
        volumes:
            - ./:/app
        environment:
            - DB_DSN
            - DB_USERNAME
            - DB_PASSWORD
        links:
            - db

    client:
        build: ./web/frontend-app
        ports:
          - 3000:3000
          - 4200:4200
        volumes:
          - ./web/frontend-app:/app
        links:
          - nginx-backend

    db:
        image: postgres:10
        ports:
            - "${DB_EXTERNAL_PORT}:5432"
        volumes:
            - "./docker/.data/db:/var/lib/postgresql"
        environment:
            PGSQL_ROOT_PASSWORD: ${PGSQL_ROOT_PASSWORD}
            PGSQL_DATABASE: ${PGSQL_DATABASE}
            PGSQL_USER: ${PGSQL_USER}
            PGSQL_PASSWORD: ${PGSQL_PASSWORD}

    nginx-frontend:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/express.conf:/etc/nginx/conf.d/default.conf
        links:
            - client

    nginx-backend:
        image: nginx
        ports:
            - 80:8080
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - server
        links:
            - server